
[formatting]
  align_entries         = true
  indent_entries        = true
  indent_tables         = true
  reorder_arrays        = true
  reorder_inline_tables = true
  reorder_keys          = true
